version: '2'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "14330:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=truenorth123!
      - MSSQL_PID=Developer
